---

- hosts: centos7
  become: true

  tasks:  
    - name: Get Disk Info ***disk-calculation***  
      #calculation will be wrong if there's a disk with MB
      shell: fdisk -l|grep /dev/ > disk && awk 'NR==1{print $2}' disk 
      args:
        executable: /bin/bash
      register: out  
    
    #- debug: var=out    

    - name: Get Disk Info ***disk-calculation***  
      #calculation will be wrong if there's a disk with MB
      shell: fdisk -l|grep /dev/sd > disk && awk '/Disk \/dev\/sd/ {print $3}' disk  > disk2
      args:
        executable: /bin/bash
      when: out.stdout ==  "/dev/sda:"

    - name: Get Disk Info ***disk-calculation***  
      #calculation will be wrong if there's a disk with MB
      shell: fdisk -l|grep /dev/vd > disk && awk '/Disk \/dev\/vd/ {print $3}' disk  > disk2
      args:
        executable: /bin/bash
      when: out.stdout ==  "/dev/vda:"

    - name: Get how many disk ***disk-calculation***
      shell: cat disk2 | wc -l
      args:
        executable: /bin/bash
      register: countline

    - name: Calculate the sum of disks ***disk-calculation***
      shell: awk '{sum+=$1} (NR%{{countline.stdout}})==0{print sum}' disk2 >> /tmp/{{ ansible_hostname }}_data.csv
      args:
        executable: /bin/bash     
