---
# this is a trivial example of how to do a nested loop.

- hosts: all
  vars:
    listvar1:
    - 'a'
    - 'b'
    - 'c'
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }}" > a.txt
      with_nested:
        - listvar1
        - [ 1, 2, 3 ]
