---

- hosts: all
  vars:
    listvar1:
      - a
      - b
      - c
    listvar2:
      - 1
      - 2
      - 3
        
  tasks:
  
- name: delete local /tmp
  shell: rm -fr /tmp/test/
  args:
    executable: /bin/bash
    warn: False
  ignore_errors: True
  delegate_to: localhost
  
- shell: echo "nested test a={{ item[0] }} b={{ item[1] }}" >> /tmp/test/a.txt
  when: listvar1 == "a"
  with_nested:
    - "{{ listvar1 }}"
    - "{{ listvar2 }}"
