---

- hosts: all
  vars:
    listvar1:
      - "a"
      - "b"
      - "c"
    listvar2:
      - 1
      - 2
      - 3
        
  tasks:  
    - shell: rm -fr /tmp/tmp/ 
      warn: False
      ignore_errors: True
      delegate_to: localhost
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }}" >> /tmp/tmp/a.txt
      #when: listvar1 == "a"
      with_nested:
        - "{{ listvar1 }}"
        - "{{ listvar2 }}"
