---
# this is a trivial example of how to do a nested loop.

- hosts: all
  vars:
    listvar1:
      - a
      - b
      - c
    listvar2:
      - 1
      - 2
      - 3
      
      
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }}" >> /tmp/a.txt
      with_nested:
        - {{ listvar1 }}
        - listvar2
