--- 
- name: Include file
  include_vars: server.yml

- shell: rm -f /tmp/x_output.csv
  warn: False
  ignore_errors: True
  delegate_to: localhost
 
- name: Check if remote port
  wait_for: host={{ item.server2 }} port={{ item.port }} timeout=1
  ignore_errors: True
  register: out
  when: item.server1 == ansible_hostname
  with_items: "{{ servers }}"
    
- debug: var=out
  
- name: Save remote port   
  shell: printf "\n,{{ item.item.server2 }} port {{ item.item.port }} is {% if item.failed %}closed{% else %}open{% endif %}"  >> /tmp/x_output.csv
  args:
    executable: /bin/bash
  when: item.item.server1 == ansible_hostname
  with_items: "{{ out.results }}"
  
