--- 
- name: Include file
  include_vars: server.yml
 
- name: Check if remote port
  wait_for: host={{ item.name }} port={{ item.port }} timeout=1
  ignore_errors: True
  register: out
  with_items: "{{ servers }}"
    
- debug: var=out
  
- name: Save remote port   
  shell: printf "\n,{{ item.item.name }} port {{ item.item.port }} is {% if item.failed %}closed{% else %}open{% endif %}"  >> /tmp/x_output.csv
  args:
    executable: /bin/bash
  with_items: "{{ out.results }}"
  
